inherit_from: .rubocop_todo.yml
AllCops:
  Include:
    - Rakefile
    - config.ru
    - lib/**/*.rake
  Exclude:
    - Gemfile
    - db/schema.rb
    - 'bin/bundle'
    - 'bin/rails'
    - 'bin/rake'