# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 386e67ea220dcaba6be87f52fabba5cb56fec53338a355121e8c2a482075870f97fe16673c576c0ef44392df67ec4c3289776e8624d0803b2f4a714ec24e3e7a

test:
  secret_key_base: 2a443ea9dfea7a81f26e43a1c13eb0a2aa330156c78748ef6701683c2e58403129fece1040095e29b513187007ee2934bd09888757b9e5e50b385353f7c6054b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
